### PR TITLE
refactored assessment form to use separate components not tabs

### PR DESCRIPTION
**Pull request by mvillis**
#123
- [x] Figure out how to determine the first tab to show
- [x] Add the observeInput component back in again
- [x] Getting the forward / back buttons at the bottom working again
- [x] decide if the intro screen stays #63 
- [x] see if there are some ajax calls that can be culled
- [x] add progress tracking back on to attribute list
- [x] smooth the transition between tabs (animation etc..)

### CODE REVIEW

**Comment by mvillis** [comment]
Trick to getting parent child stuff to work with react-router was this section:

```
                {React.cloneElement(this.props.children, {
                  template: this.state.template,
                  measurements: this.state.measurements,
                  syncMeasurement: this.syncMeasurement,
                  measureSyncActivity: this.state.measureSyncActivity
                })}
```

This is based on option 2 here https://github.com/reactjs/react-router/issues/1531#issuecomment-146514399

With AttributeList component once again owning all the syncing and share with children, all of the remaining tasks should be fairly simple to finish off.

**Comment by mvillis** [comment]
@rloomans - keep the intro screen? 
https://measuremate-pr-130.herokuapp.com/#/assessment/14/

**Comment by rloomans** [comment]
Yeah... I was thinking that the intro text on this page should come out of the template in the DB.

Also, the welcome text on the home page should be in the DB and changeable from the admin interface.

## 

Robert Loomans

On 25 Mar 2016, at 16:05, Mike Villis <notifications@github.com<mailto:notifications@github.com>> wrote:

@rloomanshttps://github.com/rloomans - keep the intro screen?
https://measuremate-pr-130.herokuapp.com/#/assessment/14/

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/mvillis/measure-mate/pull/130#issuecomment-201156924

---

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.

**Comment by mvillis** [comment]
Added #137 to dynamically change the intro text.

Will go ahead and merge this one.

**Pull request merged**
