### PR TITLE
Simplify assessments

### PR DESCRIPTION
**Pull request by rloomans**
Drop tags from assessments and refactor based on the idea that teams are mandatory

### CODE REVIEW

**Comment by mvillis** [comment]
I agree that repeating team tags on assessments is messy.

For future reporting it would be valuable for teams to be able to tag assessments so they could see assessment for particular products, squads or other subsets of their assessment.

**Comment by rloomans** [comment]
I think we can always add them back in later... for now I think they just complicate things.

**Comment by mvillis** [comment]
Ok cool. I agree it's nice and simple without it. 

could maybe hide the tag option behind a check box or even defer it to appear on the following screen.

**Comment by rloomans** [comment]
Yeah, or on the summary page or even at the finalisation step.

**Pull request merged**
