### PR TITLE
Ability to finalise an assessment

### PR DESCRIPTION
**Pull request by mvillis**
#65
- [x] update api to support status
- [x] add validation to assessment apis to support read only
- [x] add validation to measurement apis to support read only
- [x] update summary view to allow users to finalise an assessment
- [x] update list view to show the status of assessment

### CODE REVIEW

**Comment by mvillis** [comment]
@rloomans what do you think of the finalise option on the summary screen?

https://measuremate-pr-152.herokuapp.com/assessment/12/summary

At the moment it doesn't do anything.

Was thinking of making it appear once you have completed all the attributes?
What do you think?

**Comment by rloomans** [comment]
Looks good. I'll test the wording with couple of people. 

I think it should be disabled, not missing, and have a tooltip or message saying why.

**Comment by mvillis** [comment]
@rloomans - time to review.

One thing I dodged is making the Finalise Assessment Panel aware of whether you have completed all the attributes. Felt that kind of calculation would be a slow one to do every time a change was made on the screen. Tried to provide a good user flow by suggesting when they're ready they can go to the Summary panel.

**Comment by mvillis** [comment]
@rloomans nudge

keen to merge this and the other pull request 👍

**Comment by rloomans** [comment]
Looks good. Merge it.

On 19 April 2016 at 08:05, Mike Villis notifications@github.com wrote:

> @rloomans https://github.com/rloomans nudge
> 
> keen to merge this and the other pull request 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mvillis/measure-mate/pull/152#issuecomment-211600575

## 

Robert Loomans
robert@loomans.org

**Pull request merged**
