### PR TITLE
trial of enzyme (airbnb test approach for react)

### PR DESCRIPTION
**Pull request by mvillis**
#41

http://airbnb.io/enzyme/index.html
(checkout it out based on the advice from the react home page https://facebook.github.io/react/docs/test-utils.html)

it uses chai (http://chaijs.com) and mocha under the covers.

### CODE REVIEW

**Comment by mvillis** [comment]
struggling to figure out how to get both javascript and python coverage info into coveralls.
here is a version of the results when just the javascript info is passed through:
https://coveralls.io/builds/5919278

Tried the multiple language option show on this page https://pypi.python.org/pypi/coveralls. No luck.

Will keep digging.

**Comment by rloomans** [comment]
The error message I get suggests that the javascript info is not quite in the right format or is missing something:

```
$ coveralls -v --merge=coverage/coverage-final.json --output=foo.json
Missing .coveralls.yml file. Using only env variables.
No data to be merged; does the json file contain "source_files" data?
Write coverage report to file...
...
```

**Comment by mvillis** [comment]
@rloomans using the coveralls-lcov ruby gem / cli does the trick and the coverage data is merged successfully. need to update the readme with some info. 

anything else before I merge? seems like a reasonable spot to start

**Comment by rloomans** [comment]
Looks good to me. Merge it.

**Pull request merged**
