### PR TITLE
Boom - the switch to a full single page js web app powered by gulp

### PR DESCRIPTION
**Pull request by mvillis**
move js out into client package & package using gulp
#122 #122 #27
- [x] fix mobile view (think something is happening with the bundling of css - it's stripping the media)
- [x] get agreement from @rloomans that he is happy to go full steam ahead with http://standardjs.com
- [x] confirm with @rloomans that the README.md does accurately describe a setup process

### CODE REVIEW

**Comment by mvillis** [comment]
.....working but the bundle.js file is extraordinary!!!!!!!!

i'm guessing it's not minified and maybe I'm pulling in some crazy dependencies into it I don't need.

Since moving to the https://github.com/feross/standard linter there's hundreds of violations to check up on too.

**Comment by mvillis** [comment]
got it down to 2.3 mb by adding an uglify compression step.

**Comment by mvillis** [comment]
an old but good read on asynchronous loading:
http://esa-matti.suuronen.org/blog/2013/04/15/asynchronous-module-loading-with-browserify/

an another option to reduce load times is to follow the info on plotly. In the Module section on this page is tells you how to restrict it to just what you need https://www.npmjs.com/package/plotly.js

**Comment by mvillis** [comment]
> an another option to reduce load times is to follow the info on plotly. In the Module section on this page is tells you how to restrict it to just what you need https://www.npmjs.com/package/plotly.js

Implemented this one. Down to 1.5 mb

**Comment by mvillis** [comment]
and down to 364kb through the wonders of gzipping!

**Comment by rloomans** [comment]
I think that we ignore the mobile view for now... Merge it!

**Pull request merged**
