### PR TITLE
Add actions

### PR DESCRIPTION
**Pull request by rloomans**

### CODE REVIEW

**Comment by mvillis** [comment]
not a fan of rebasing?

**Comment by rloomans** [comment]
Rebasing doesn't work if you've already pushed the branch :)

On 28 March 2016 at 20:56, Mike Villis notifications@github.com wrote:

> not a fan of rebasing?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/mvillis/measure-mate/pull/136#issuecomment-202340434

## 

Robert Loomans
robert@loomans.org

**Comment by mvillis** [comment]
> Rebasing doesn't work if you've already pushed the branch :)

I just force push if i'm working solo on a branch.

....Feel the power....

**Comment by rloomans** [comment]
Benched for the moment. The single action per attribute works for now.

**Comment by rloomans** [comment]
Can it... we'll create a new PR when we get back around to it.

**Pull request closed without merging**
