### PR TITLE
Add more fixtures

### PR DESCRIPTION
**Pull request by rloomans**
Add more incomplete fixtures for templates (Governance and DevOps) and make the description for ratings have a selectable CSS style

### CODE REVIEW

**Comment by mvillis** [comment]
nice work @rloomans !

**Comment by rloomans** [comment]
Except that I've broken the demo. Where do I add steps to the Heroku deploy? I need to add a manage.py migrate. 

## 

Robert Loomans

**Comment by mvillis** [comment]
i can't see an obvious way to include this in the pipeline.

you can do it manually using the heroku run command:

https://devcenter.heroku.com/articles/getting-started-with-django#syncing-the-database

Will keep looking at other options. For now we'd be pretty safe in always running a python mange.py migrate on every deploy.

**Comment by rloomans** [comment]
Yeah, I ran it manually when I got home... Hadn't gotten the heroku CLI installed at work. 

That was my plan: for now running the migrate every time shouldn't be a problem. 

## 

Robert Loomans

**Pull request merged**
